package com.healthtracker.chw.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Disease Report model
 * Represents a disease case report generated from an encounter
 * 
 * Relationships:
 * - Generated by 1 Encounter (Many-to-One)
 * - Aggregates many MeasureReports (One-to-Many)
 * - Produces 1 RiskAssessment (One-to-One)
 */
public class DiseaseReport {
    private String reportId;
    private String diseaseType;
    private Date reportDate;
    private String status; // pending, confirmed, resolved
    private Encounter encounter; // Many-to-One relationship
    private List<MeasureReport> measureReports; // One-to-Many relationship
    private RiskAssessment riskAssessment; // One-to-One relationship

    // Default constructor for Gson/Retrofit
    public DiseaseReport() {
        this.measureReports = new ArrayList<>();
    }

    // Constructor with required fields
    public DiseaseReport(String reportId, String diseaseType, Date reportDate, String status) {
        this.reportId = reportId;
        this.diseaseType = diseaseType;
        this.reportDate = reportDate;
        this.status = status;
        this.measureReports = new ArrayList<>();
    }

    // Full constructor
    public DiseaseReport(String reportId, String diseaseType, Date reportDate, String status,
                        Encounter encounter, List<MeasureReport> measureReports,
                        RiskAssessment riskAssessment) {
        this.reportId = reportId;
        this.diseaseType = diseaseType;
        this.reportDate = reportDate;
        this.status = status;
        this.encounter = encounter;
        this.measureReports = measureReports != null ? measureReports : new ArrayList<>();
        this.riskAssessment = riskAssessment;
    }

    // Getters and Setters
    public String getReportId() {
        return reportId;
    }

    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    public String getDiseaseType() {
        return diseaseType;
    }

    public void setDiseaseType(String diseaseType) {
        this.diseaseType = diseaseType;
    }

    public Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Encounter getEncounter() {
        return encounter;
    }

    public void setEncounter(Encounter encounter) {
        this.encounter = encounter;
    }

    public List<MeasureReport> getMeasureReports() {
        return measureReports;
    }

    public void setMeasureReports(List<MeasureReport> measureReports) {
        this.measureReports = measureReports != null ? measureReports : new ArrayList<>();
    }

    public void addMeasureReport(MeasureReport measureReport) {
        if (measureReports == null) {
            measureReports = new ArrayList<>();
        }
        measureReports.add(measureReport);
    }

    public RiskAssessment getRiskAssessment() {
        return riskAssessment;
    }

    public void setRiskAssessment(RiskAssessment riskAssessment) {
        this.riskAssessment = riskAssessment;
    }
}

